#!/usr/bin/env python3
"""
Generate the docs pages and site data that are copies of the contract.

    python scripts/gen_docs.py           # write the files
    python scripts/gen_docs.py --check   # exit 1 if any file differs from what would be written

A method cannot exist in the code and be missing from the docs, and the judge
prompt on the site cannot drift from the one validators read, because both are
written from contracts/clearance.py by this script, and a test runs --check.

Writes:
  web/content/docs/reference/contract.mdx   every public method, from the source
  web/content/docs/reference/errors.mdx     every refusal sentence, from the source
  web/content/docs/more/judge-prompt.mdx    the judge prompt, word for word
  web/lib/contract.generated.json           limits, verdicts and the prompt, for the site
"""

from __future__ import annotations

import ast
import hashlib
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTRACT = ROOT / "contracts" / "clearance.py"
DOCS = ROOT / "web" / "content" / "docs"

HEADER = "{/* Generated by scripts/gen_docs.py from contracts/clearance.py. Do not edit by hand. */}\n\n"


def load():
    source = CONTRACT.read_text(encoding="utf-8")
    return source, ast.parse(source)


def constant(tree: ast.Module, name: str):
    for node in tree.body:
        if isinstance(node, ast.Assign) and ast.unparse(node.targets[0]) == name:
            try:
                return ast.literal_eval(node.value)
            except ValueError:
                return ast.unparse(node.value)
    raise KeyError(name)


def contract_class(tree: ast.Module) -> ast.ClassDef:
    return next(n for n in tree.body if isinstance(n, ast.ClassDef) and n.name == "Clearance")


def kind_of(node: ast.FunctionDef) -> str:
    for deco in node.decorator_list:
        text = ast.unparse(deco)
        if text == "gl.public.write":
            return "write"
        if text == "gl.public.write.payable":
            return "payable"
        if text == "gl.public.view":
            return "view"
    return ""


def mdx_text(text: str) -> str:
    """Plain prose into MDX: braces and angle brackets would be read as code."""
    return text.replace("{", "&#123;").replace("}", "&#125;").replace("<", "&lt;").replace(">", "&gt;")


def signature(node: ast.FunctionDef) -> str:
    args = ", ".join(f"{a.arg}: {ast.unparse(a.annotation)}" for a in node.args.args[1:])
    returns = ast.unparse(node.returns) if node.returns else "None"
    return f"{node.name}({args}) -> {returns}"


def methods(tree: ast.Module) -> list[dict]:
    out = []
    for node in contract_class(tree).body:
        if isinstance(node, ast.FunctionDef) and kind_of(node):
            doc = ast.get_docstring(node) or ""
            out.append(
                {
                    "name": node.name,
                    "kind": kind_of(node),
                    "signature": signature(node),
                    "args": [{"name": a.arg, "type": ast.unparse(a.annotation)} for a in node.args.args[1:]],
                    "returns": ast.unparse(node.returns) if node.returns else "None",
                    "doc": " ".join(doc.split()),
                    "line": node.lineno,
                }
            )
    return out


def refusals(tree: ast.Module) -> list[dict]:
    """Every UserError sentence, with the method it can come from. Dynamic parts read as '…'."""

    def text_of(expr: ast.AST) -> tuple[str, str]:
        parts: list[str] = []

        def walk(e: ast.AST) -> None:
            if isinstance(e, ast.BinOp) and isinstance(e.op, ast.Add):
                walk(e.left)
                walk(e.right)
            elif isinstance(e, ast.Constant) and isinstance(e.value, str):
                parts.append(e.value)
            elif isinstance(e, ast.Name) and e.id in ("E", "L"):
                parts.append("\x00" + e.id)
            else:
                parts.append("…")

        walk(expr)
        prefix = parts[0][1:] if parts and parts[0].startswith("\x00") else ""
        body = "".join(p for p in parts if not p.startswith("\x00"))
        return prefix, body

    owner: dict[int, str] = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef):
            for inner in ast.walk(node):
                if hasattr(inner, "lineno"):
                    owner.setdefault(inner.lineno, node.name)
    rows: dict[tuple, dict] = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.Call) and ast.unparse(node.func) == "gl.vm.UserError" and node.args:
            prefix, body = text_of(node.args[0])
            key = (prefix, body)
            where = owner.get(node.lineno, "")
            row = rows.setdefault(key, {"prefix": prefix, "text": body, "where": []})
            if where and where not in row["where"]:
                row["where"].append(where)
    return sorted(rows.values(), key=lambda r: (r["prefix"], r["text"]))


def build() -> dict[pathlib.Path, str]:
    source, tree = load()
    judge = constant(tree, "JUDGE")
    judge_sha = hashlib.sha256(judge.encode("utf-8")).hexdigest()
    listed = methods(tree)
    errors = refusals(tree)
    files: dict[pathlib.Path, str] = {}

    # -- contract reference --------------------------------------------------
    kinds = {"write": "write", "payable": "write, payable", "view": "view"}
    lines = [
        "---",
        "title: Contract reference",
        "description: Every public method of contracts/clearance.py, generated from the source.",
        "---",
        "",
        HEADER.strip(),
        "",
        f"One contract, {len(listed)} methods: {sum(1 for m in listed if m['kind'] != 'view')} writes and "
        f"{sum(1 for m in listed if m['kind'] == 'view')} views. This page is written from the contract source by "
        "`scripts/gen_docs.py`, and a test fails if the two drift, so a method cannot exist in code and be missing here.",
        "",
        "Views return JSON text. An unknown id reads as `{\"found\": false}` rather than an error, because a view that "
        "raises reaches a client only as \"execution failed\".",
        "",
        "| Method | Kind | What it does |",
        "|---|---|---|",
    ]
    for m in listed:
        first = mdx_text(m["doc"].split(". ")[0].rstrip(".")) + "."
        lines.append(f"| [`{m['name']}`](#{m['name'].replace('_', '-')}) | {kinds[m['kind']]} | {first} |")
    lines.append("")
    for m in listed:
        lines += [
            f"## {m['name']}",
            "",
            "```python",
            m["signature"],
            "```",
            "",
            f"**{kinds[m['kind']].capitalize()}.** {mdx_text(m['doc'])}",
            "",
        ]
        own = [e for e in errors if m["name"] in e["where"]]
        if own:
            lines.append("Refusals raised in the method itself (helpers such as the tier and text checks add their own, listed on the Errors page):")
            lines.append("")
            for e in own:
                lines.append(f"- `[{'EXPECTED' if e['prefix'] == 'E' else 'LLM_ERROR'}] {e['text']}`")
            lines.append("")
        lines.append(
            f"[Source, line {m['line']}](https://github.com/meitipro/clearance/blob/main/contracts/clearance.py#L{m['line']})"
        )
        lines.append("")
    files[DOCS / "reference" / "contract.mdx"] = "\n".join(lines)

    # -- errors --------------------------------------------------------------
    lines = [
        "---",
        "title: Errors",
        "description: Every refusal the contract can raise, generated from the source.",
        "---",
        "",
        HEADER.strip(),
        "",
        "A refused write still reaches consensus: validators agree the refusal is the right result, and the transaction "
        "reads ACCEPTED. The site counts a write as done only when the status is ACCEPTED or FINALIZED **and** the "
        "execution returned; otherwise it shows the sentence below, which the transaction carries in its result payload.",
        "",
        "`[EXPECTED]` refusals are deterministic and identical on every validator. `[LLM_ERROR]` means a model answer "
        "could not be read; validators then disagree on purpose, so the round rotates to a committee that can answer, "
        "and nothing defaults to a verdict.",
        "",
        "| Refusal | Raised in |",
        "|---|---|",
    ]
    for e in errors:
        tag = "EXPECTED" if e["prefix"] == "E" else "LLM_ERROR"
        where = ", ".join(f"`{w}`" for w in e["where"])
        lines.append(f"| `[{tag}] {e['text']}` | {where} |")
    lines.append("")
    files[DOCS / "reference" / "errors.mdx"] = "\n".join(lines)

    # -- judge prompt --------------------------------------------------------
    lines = [
        "---",
        "title: The judge prompt, word for word",
        "description: The exact text every validator's model reads, copied from the contract.",
        "---",
        "",
        HEADER.strip(),
        "",
        "This is the `JUDGE` constant in `contracts/clearance.py`, the text of section 3 of the build spec. The four "
        "values in braces are filled per request. The license, the tiers and the use are fenced before they are "
        "inserted: every `<` becomes `(` and every `>` becomes `)`, so no text can close its own block and open a "
        "forged one. Storage keeps what was written; only the prompt copy is fenced.",
        "",
        "```text",
        judge.replace("{{", "{").replace("}}", "}"),
        "```",
        "",
        f"SHA-256 of the constant: `{judge_sha}`.",
        "",
        "When a license has no paid tier, the tiers block reads:",
        "",
        "```text",
        constant(tree, "NO_TIERS"),
        "```",
        "",
        "## How validators agree",
        "",
        "The leader asks its model and returns four strings: verdict, tier, conditions and reason. Each validator asks "
        "its own model the same prompt and agrees only when its own **verdict and tier id** match the leader's. The "
        "conditions and the reason are stored from the leader's answer for display and are never compared.",
        "",
        "An answer that cannot be read (not JSON, a label outside the four, or PAID without a tier of this license) is "
        "retried once, then fails the round. It never becomes a verdict.",
        "",
    ]
    files[DOCS / "more" / "judge-prompt.mdx"] = "\n".join(lines)

    # -- site data -----------------------------------------------------------
    data = {
        "source": "contracts/clearance.py",
        "judge": judge.replace("{{", "{").replace("}}", "}"),
        "judgeSha256": judge_sha,
        "noTiers": constant(tree, "NO_TIERS"),
        "verdicts": list(constant(tree, "VERDICTS")),
        "kinds": list(constant(tree, "KINDS")),
        "limits": {
            "title": constant(tree, "MAX_TITLE"),
            "link": constant(tree, "MAX_LINK"),
            "creator": constant(tree, "MAX_CREATOR"),
            "license": constant(tree, "MAX_LICENSE"),
            "tiers": constant(tree, "MAX_TIERS"),
            "tierId": constant(tree, "MAX_TIER_ID"),
            "tierName": constant(tree, "MAX_TIER_NAME"),
            "tierScope": constant(tree, "MAX_TIER_SCOPE"),
            "use": constant(tree, "MAX_USE"),
            "page": constant(tree, "MAX_PAGE"),
        },
        "holdSeconds": 7 * 86400,
        "methods": [{k: m[k] for k in ("name", "kind", "signature", "doc")} for m in listed],
    }
    files[ROOT / "web" / "lib" / "contract.generated.json"] = json.dumps(data, indent=2, ensure_ascii=False) + "\n"

    files[DOCS / "more" / "evaluation.mdx"] = evaluation_page()
    files[DOCS / "reference" / "addresses.mdx"] = addresses_page()
    files.update(synced_includes())
    return files


# -- evaluation, from eval/results.json -----------------------------------------------
def evaluation_page() -> str:
    results = json.loads((ROOT / "eval" / "results.json").read_text(encoding="utf-8"))
    golden = json.loads((ROOT / "eval" / "golden.json").read_text(encoding="utf-8"))
    explorer = results["explorer"]
    final = {a["case"]: a for a in results["attempts"] if a.get("verdict")}

    def hit(a: dict) -> bool:
        return (a["verdict"], a["tier"]) == (a["expected"]["verdict"], a["expected"]["tier"])

    held = [c for c in golden["cases"] if c.get("held_out")]
    main = [c for c in golden["cases"] if not c.get("held_out")]
    g = sum(1 for c in main if c["id"] in final and hit(final[c["id"]]))
    h = sum(1 for c in held if c["id"] in final and hit(final[c["id"]]))
    lines = [
        "---",
        "title: Evaluation results with transactions",
        "description: Twelve cases through real consensus on the deployed contract, reported as they came out.",
        "---",
        "",
        "{/* Generated by scripts/gen_docs.py from eval/results.json. Do not edit by hand. */}",
        "",
        f"Every case below is one `ask` transaction on the deployed contract, "
        f"[`{results['contract']}`]({explorer}/address/{results['contract']}), and every verdict was read back from the "
        "contract with `get_request`. Each case's license was published as a work of its own first, from a separate "
        "account, so the judge read exactly what a real request would.",
        "",
        f"- **Golden set: {g} of {len(main)}** matched the expected answer.",
        f"- **Held-out cases: {h} of {len(held)}** matched.",
        f"- `eval/golden.json` was hashed and timestamped before the first run: sha256 `{results['golden_sha256']}`, "
        f"locked at {results['golden_locked_at']}.",
        f"- The judge prompt is the spec's, word for word (sha256 `{results['judge_sha256']}`). Nothing was tuned.",
        "",
        "H1 to H3 were written with the golden set, before the first run, and each was run once. H1 and H3 are borderline "
        "on purpose. The miss is reported as it came out.",
        "",
        "| Case | License, in short | Use | Expected | Got | Transaction |",
        "|---|---|---|---|---|---|",
    ]
    for c in golden["cases"]:
        a = final.get(c["id"])
        exp = c["expected"]["verdict"] + (f" · {c['expected']['tier']}" if c["expected"]["tier"] else "")
        if not a:
            lines.append(f"| {c['id']} | {mdx_text(c['title'])} | {mdx_text(c['use'])} | {exp} | not run | |")
            continue
        got = a["verdict"] + (f" · {a['tier']}" if a["tier"] else "")
        mark = "✓" if hit(a) else "✗ miss"
        short_license = c["title"].split(": ", 1)[-1]
        lines.append(
            f"| {c['id']}{' (held out)' if c.get('held_out') else ''} | {mdx_text(short_license)} | {mdx_text(c['use'])} | {exp} | "
            f"**{got}** {mark} | [{a['tx'][:10]}…]({explorer}/tx/{a['tx']}) |"
        )
    lines += ["", "## The reasons", "", "The leader's one-sentence reason for each answer. Reasons are stored for display and are never compared between validators.", ""]
    for c in golden["cases"]:
        a = final.get(c["id"])
        if a:
            cond = f" Conditions: {mdx_text(a['conditions'])}" if a.get("conditions") else ""
            lines.append(f"- **{c['id']}**: {mdx_text(a['reason'])}{cond}")
    lines += [
        "",
        "## Reproduce",
        "",
        "```bash",
        "python eval/run_golden.py            # the nine golden cases not yet decided",
        "python eval/run_golden.py H1 H2 H3   # the held-out cases, once",
        "```",
        "",
        "The script refuses to run if `eval/golden.json` no longer matches its locked hash, never sends a decided case "
        "again, and saves each attempt before printing it. Every attempt is in `eval/results.json`.",
        "",
    ]
    return "\n".join(lines)


# -- addresses, from contracts/FROZEN.json --------------------------------------------
def addresses_page() -> str:
    entry = json.loads((ROOT / "contracts" / "FROZEN.json").read_text(encoding="utf-8"))["deployments"]["studio-next"]
    explorer = entry["explorer"]
    lines = [
        "---",
        "title: Addresses and network",
        "description: The deployed contract, its source hash and the network it runs on.",
        "---",
        "",
        "{/* Generated by scripts/gen_docs.py from contracts/FROZEN.json. Do not edit by hand. */}",
        "",
        "| | |",
        "|---|---|",
        f"| Contract | [`{entry['clearance']}`]({explorer}/address/{entry['clearance']}) |",
        f"| Deploy transaction | [`{entry['clearance_tx']}`]({explorer}/tx/{entry['clearance_tx']}) |",
        f"| Deployed | {entry['deployed_at']} |",
        f"| Deployer | [`{entry['clearance_deployer']}`]({explorer}/address/{entry['clearance_deployer']}) |",
        f"| Source | `contracts/clearance.py`, sha256 `{entry['clearance_sha256']}` |",
        f"| Runtime | `{entry['runtime']}` (GenVM SDK v0.3) |",
        "| Network | GenLayer Studio Next |",
        f"| Chain id | {entry['chain_id']} (`0x{entry['chain_id']:x}`) |",
        "| RPC | `https://studio-next.genlayer.com/api` |",
        f"| Explorer | {explorer} |",
        "| Currency | GEN, 18 decimals. Test GEN from the site's faucet. |",
        "",
        "## Check the deployment yourself",
        "",
        "`scripts/verify.py` reads the source back off the chain with `gen_getContractCode`, compares it byte for byte "
        "with `contracts/clearance.py`, checks the sha256 against `contracts/FROZEN.json`, and lints the bytes that came "
        "back with genvm-lint:",
        "",
        "```bash",
        "python scripts/verify.py",
        "```",
        "",
        "## Add the network to a wallet",
        "",
        "The site does this for you. By hand: network name `GenLayer Studio Next`, RPC "
        f"`https://studio-next.genlayer.com/api`, chain id `{entry['chain_id']}`, currency `GEN`, explorer `{explorer}`.",
        "",
        "Studio Next charges a fee deposit on every write, from the SDK's estimate; most of it is refunded when the "
        "transaction finalizes. Reads are free. The RPC rate-limits each IP, so the site caches shared reads for 20 seconds "
        "and drops the cache after each write.",
        "",
    ]
    return "\n".join(lines)


# -- code samples copied from files that run -----------------------------------------
INCLUDE_OPEN = "{/* include: "
INCLUDE_CLOSE = "{/* end include */}"
LANGS = {".mjs": "js", ".js": "js", ".ts": "ts", ".py": "python", ".json": "json"}


def synced_includes() -> dict[pathlib.Path, str]:
    """
    Every `{/* include: path */}` ... `{/* end include */}` block in the docs is
    replaced by the file at web/<path>, fenced. A sample in the docs is then the
    code in the repository, which is the code that was run.
    """
    out: dict[pathlib.Path, str] = {}
    generated = {DOCS / "reference" / "contract.mdx", DOCS / "reference" / "errors.mdx", DOCS / "more" / "judge-prompt.mdx",
                 DOCS / "more" / "evaluation.mdx", DOCS / "reference" / "addresses.mdx"}
    for page in sorted(DOCS.rglob("*.mdx")):
        if page in generated:
            continue
        text = page.read_text(encoding="utf-8")
        if INCLUDE_OPEN not in text:
            continue
        parts = []
        rest = text
        while INCLUDE_OPEN in rest:
            before, _, after = rest.partition(INCLUDE_OPEN)
            path_text, _, after = after.partition(" */}")
            _, _, after = after.partition(INCLUDE_CLOSE)
            source = ROOT / "web" / path_text.strip()
            code = source.read_text(encoding="utf-8").rstrip("\n")
            lang = LANGS.get(source.suffix, "")
            parts.append(before + INCLUDE_OPEN + path_text + " */}\n```" + lang + ' title="' + path_text.strip() + '"\n' + code + "\n```\n" + INCLUDE_CLOSE)
            rest = after
        parts.append(rest)
        out[page] = "".join(parts)
    return out


def main() -> int:
    check = "--check" in sys.argv
    stale = []
    for path, text in build().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != text:
            stale.append(path.relative_to(ROOT).as_posix())
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8", newline="\n")
    if check:
        if stale:
            print("stale generated files, run python scripts/gen_docs.py:\n  " + "\n  ".join(stale))
            return 1
        print("generated files match the contract")
        return 0
    print("wrote " + (", ".join(stale) if stale else "nothing, all current"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
